[package]
name         = "osu-map-cleaner"
version      = "0.1.0"
edition      = "2024"
rust-version = "1.85"
description  = "Filter osu! beatmaps with an expression and move matched difficulties or whole sets to the recycle bin."
repository   = "https://github.com/lxl66566/osu-map-cleaner"
license      = "MIT OR Apache-2.0"
keywords     = ["beatmap", "cleaner", "cli", "osu"]
categories   = ["command-line-utilities"]
include      = ["/CHANGELOG.md", "/LICENSE-*", "/README.md", "/benches/**", "/src/**", "/tests/**"]

[dependencies]
anyhow    = "1.0.104"
clap      = { version = "4.6.7", features = ["derive"] }
hex-simd  = "0.8.0"
inquire   = "0.9.4"
md-5      = "0.11.0"
rayon = "1.12.0"
rosu-pp = "4.0.1"
thiserror = "2.0.20"
trash     = "5.2.9"

[lints.clippy]
all                     = { level = "warn", priority = -1 }
cargo                   = { level = "warn", priority = -1 }
doc_markdown            = "allow"
missing_errors_doc      = "allow"
missing_panics_doc      = "allow"
multiple_crate_versions = "allow"
pedantic                = { level = "warn", priority = -1 }
wildcard_imports        = "allow"

[lints.rust]
unsafe_code           = "allow"
unused_qualifications = "warn"

[dev-dependencies]
tempfile = "3.27.0"

# If you are building bin target, uncomment this
# [profile.release]
# lto       = true
# opt-level = "s"
# panic     = "abort"
# strip     = true
